### ISSUE TITLE
Couldn't get it to work

### ISSUE THREAD

**Issue by brecke** [ensky/taiga-contrib-ldap-auth#1]
Hi there,

Thank you for doing this. I've tried installing it but no luck in installing via pip

```
Downloading/unpacking taiga-contrib-ldap-auth
  Could not find any downloads that satisfy the requirement taiga-contrib-ldap-auth
Cleaning up...
No distributions at all found for taiga-contrib-ldap-auth
Storing debug log for failure in /home/taiga/.pip/pip.log
```

Am I doing anything wrong? Is there any workaround to this?

**Comment by jespino** [comment]
It isn't work yet. It will work in the next taiga release. On other hand
the python pip package isn't published yet.

Tomorrow I will modify the Readme to include a warning about this.

**Comment by brecke** [comment]
ok thanks man. And good luck!

**Comment by linuxconsole** [comment]
Hi,

Since taiga 1.6 it's released, i tried installing it but without any luck, i'm getting the same error.

**Comment by donald-slagle** [comment]
Just tried on the 1.6 release of Taiga, seems that the pip package still hasn't been published. Waiting on this plugin has been my only reason for not going live with my Taiga install. It would be great to see this pip package go live so everyone can start using.

**Comment by ensky** [comment]
@linuxconsole @donald-slagle I've just uploaded it to PyPI. You can try it now.

**Comment by jolinx** [comment]
you should use the follwing comand:
`sudo pip3 install taiga-contrib-ldap-auth`
