### ISSUE TITLE
Taiga Login page blank after adding ldap plugin

### ISSUE THREAD

**Issue by kierenalt255** [ensky/taiga-contrib-ldap-auth#13]
Hello.

Our freshly installed Taiga login page only had the top banner on the login page after adding the ldap plugin. Before adding the ldap plugin Taiga was fine. 
I've update dist/js/conf.json and settings/local.py as described and gunicorn.stderr.log has no errors. I also set "publicRegisterEnabled": false in both dist/js/conf.json and settings/local.py. Restarted all services and still a blank login page(with top banner)...

I also tried 

curl -X POST \
  -H "Content-Type: application/json" \
  -d '{
          "type": "ldap",
          "username": "USERNAME",
          "password": "PASSWORD"
      }' \
  http://127.0.0.1/api/v1/auth

and I get back the following
{"_error_type": "taiga.base.exceptions.BadRequest", "_error_message": "invalid login type"}
Any suggesstions would be greatly appreciated

**Comment by artlepool** [comment]
Hi @kierenalt255 

It looks like the ldap plugin isn't registering itself with Taiga correctly. Could you share your settings/local.py file (without any sensitive information obviously) so I can have a check and compare with mine?

Also, have you tried loading the login page with the browser's Developer Tools open? Worth a try to see if there are any javascript errors happening client-side, and to check any requests to the server too.

**Comment by kierenalt255** [comment]
Hello @artlepool 

The following is our settings/local.py file

> from .commons import *
> 
> DATABASES = {
>    'default': {
>        'ENGINE': 'transaction_hooks.backends.postgresql_psycopg2',
>        'NAME': 'taiga',
>        'USER': 'taiga',
>        'PASSWORD': 'bomb'
>    }
> }
> 
> MEDIA_URL = "http://ourserver/media/"
> STATIC_URL = "http://ourserver/static/"
> ADMIN_MEDIA_PREFIX = "http://ourserver/static/admin/"
> SITES["front"]["scheme"] = "http"
> SITES["front"]["domain"] = "ourserver"
> 
> SECRET_KEY = "oursecret"
> 
> DEBUG = True
> TEMPLATE_DEBUG = False
> 
> PUBLIC_REGISTER_ENABLED = False
> 
> DEFAULT_FROM_EMAIL = "no-reply@example.com"
> SERVER_EMAIL = DEFAULT_FROM_EMAIL
> 
> INSTALLED_APPS += ["taiga_contrib_ldap_auth"]
> 
> LDAP_SERVER = 'ldap://query.domain.company.com'
> LDAP_PORT = 389
> 
> # Full DN of the service account use to connect to LDAP server and search for login user's account entry
> # If LDAP_BIND_DN is not specified, or is blank, then an anonymous bind is attempated
> LDAP_BIND_DN = 'CN=serviceaccount,OU=ServiceAccounts,OU=users,DC=domain,DC=company,DC=com'
> LDAP_BIND_PASSWORD = 'ourpass'   # eg.
> Starting point within LDAP structure to search for login user
> LDAP_SEARCH_BASE = 'DC=domain,DC=company,DC=com'
> LDAP property used for searching, ie. login username needs to match value in sAMAccountName property in LDAP
> LDAP_SEARCH_PROPERTY = 'sAMAccountName'
> LDAP_SEARCH_SUFFIX = None # '@example.com'
> 
> # Names of LDAP properties on user account to get email and full name
> LDAP_EMAIL_PROPERTY = 'mail'
> LDAP_FULL_NAME_PROPERTY = 'name'

Also, I had developer tools loaded for the browser to see if any dependencies were missing, I've included a screen shot below.

![ldap_taiga](https://cloud.githubusercontent.com/assets/4288525/8970066/c188bd1e-368a-11e5-8661-85282ca29dbc.png)

I appreciate your help, thanks, regards, Kieren.

**Comment by artlepool** [comment]
That all looks good to me. Hmm.

What is the output of the "pip list" command, when you run it at a bash prompt in the same virtual environment that taiga-back is running in?

**Comment by kierenalt255** [comment]
Hello @artlepool 

Here is our pip list

> $ pip list
> amqp (1.4.6)
> anyjson (0.3.3)
> billiard (3.3.0.20)
> bleach (1.4)
> celery (3.1.17)
> cssselect (0.9.1)
> cssutils (1.0)
> diff-match-patch (20121119)
> Django (1.7.8)
> django-ipware (0.1.0)
> django-jinja (1.0.4)
> django-pgjson (0.2.2)
> django-pglocks (1.0.2)
> django-picklefield (0.3.1)
> django-sampledatahelper (0.2.2)
> django-sites (0.8)
> django-sr (0.0.4)
> django-transaction-hooks (0.2)
> django-transactional-cleanup (0.1.14)
> djmail (0.10.0)
> djorm-pgarray (1.0.4)
> easy-thumbnails (2.1)
> fn (0.2.13)
> gunicorn (19.3.0)
> html5lib (0.999999)
> Jinja2 (2.7.2)
> kombu (3.0.26)
> lxml (3.4.1)
> Markdown (2.4.1)
> MarkupSafe (0.23)
> Pillow (2.9.0)
> pip (7.1.0)
> premailer (2.8.1)
> psycopg2 (2.5.4)
> Pygments (1.6)
> pytz (2014.4)
> raven (5.1.1)
> redis (2.10.3)
> requests (2.4.1)
> setuptools (18.0.1)
> six (1.8.0)
> Unidecode (0.4.16)
> (taiga)

At the moment we dont have "Async Tasks" nor "Events" installed/enabled. I'm not sure if that might be related. We're also running this on RHEL 6.5 x64.

Thanks for your time, regards, Kieren.

**Comment by artlepool** [comment]
The list doesn't seem to contain the ldap plugin which might explain why Taiga is returning a "invalid login type" error, meaning that the plugin hasn't registered with the Taiga plugin system when the services start up.

Our "pip list" output looks like the following

> amqp (1.4.6)
> anyjson (0.3.3)
> billiard (3.3.0.20)
> bleach (1.4)
> celery (3.1.17)
> cssselect (0.9.1)
> cssutils (1.0)
> diff-match-patch (20121119)
> Django (1.7.8)
> django-ipware (0.1.0)
> django-jinja (1.0.4)
> django-pgjson (0.2.2)
> django-pglocks (1.0.2)
> django-picklefield (0.3.1)
> django-sampledatahelper (0.2.2)
> django-sites (0.8)
> django-sr (0.0.4)
> django-transaction-hooks (0.2)
> django-transactional-cleanup (0.1.14)
> djmail (0.10.0)
> djorm-pgarray (1.0.4)
> easy-thumbnails (2.1)
> enum34 (1.0)
> fn (0.2.13)
> gunicorn (19.3.0)
> html5lib (0.999999)
> Jinja2 (2.7.2)
> kombu (3.0.26)
> ldap3 (0.9.8.7)
> lxml (3.4.1)
> Markdown (2.4.1)
> MarkupSafe (0.23)
> Pillow (2.5.3)
> pip (7.1.0)
> premailer (2.8.1)
> psycopg2 (2.5.4)
> pyasn1 (0.1.8)
> Pygments (1.6)
> pytz (2014.4)
> raven (5.1.1)
> redis (2.10.3)
> requests (2.4.1)
> setuptools (18.0.1)
> six (1.8.0)
> taiga-contrib-ldap-auth (0.0.5)
> Unidecode (0.4.16)

with the plugin showing in the list between `six` and `Unidecode`

Did you activate your python virtual environment before running the command `pip install taiga-contrib-ldap-auth`?
The plugin will need to be installed in the same 'context' or virtual environment that the taiga-back app is running in.
