### ISSUE TITLE
 Non-ASCII character '\xc3' in file taiga_contrib_ldap_auth/__init__.py

### ISSUE THREAD

**Issue by rawbean** [ensky/taiga-contrib-ldap-auth#14]
SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_ldap_auth/**init**.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

proposal: Add the following statement right at the begining, before all import statements.
# -- coding: utf-8 --

**Comment by ensky** [comment]
same as #10
try using python3.

**Comment by rawbean** [comment]
if the version 2.7 and 3.x of python exist but the default is 2.7,  we need to install this package use pip3, please find the script below:

 pip3 install taiga-contrib-ldap-auth
