### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by codertao** [ensky/taiga-contrib-ldap-auth#16]
The underlying LDAP library supports ssl via the use_ssl connection constructor parameter; but no config entry is provided to set that.

**Comment by artlepool** [comment]
Hey @codertao , see pull request #19  - does this work for you?

It doesn't specifically validate a server certificate in this version but that could come at a future date...

**Comment by mgrobelin** [comment]
seems to work for me...
LDAP_SERVER = 'ldaps://host.mycomp.internal'
LDAP_PORT = 636

**Comment by ensky** [comment]
merged
