### ISSUE TITLE
ldap username/email or password are incorrect

### ISSUE THREAD

**Issue by idanshahar** [ensky/taiga-contrib-ldap-auth#23]
I am trying to connect self hosted taiga.io to a public ldap server.
it seems that the connection worked but users cannot login to taiga.
this is the ldap server details:
http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/

this is my configuration on taiga/taiga-back/local.py:

from .common import *

MEDIA_URL = "/media/"
STATIC_URL = "/static/"

SITES["front"]["domain"] = "localhost:8000"

DEBUG = True
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "no-reply@example.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_USE_TLS = False
# EMAIL_HOST = "localhost"
# EMAIL_HOST_USER = ""
# EMAIL_HOST_PASSWORD = ""
# EMAIL_PORT = 25

  INSTALLED_APPS += ["taiga_contrib_ldap_auth"]

```
LDAP_SERVER = 'ldap://ldap.forumsys.com'
  LDAP_PORT = 389

    # Full DN of the service account use to connect to LDAP server and search for login user's account entry
      # If LDAP_BIND_DN is not specified, or is blank, then an anonymous bind is attempated
        LDAP_BIND_DN = 'cn=read-only-admin,dc=example,dc=com'
          LDAP_BIND_PASSWORD = 'password'   
            # Starting point within LDAP structure to search for login user
              LDAP_SEARCH_BASE = 'ou=mathematicians,dc=example,dc=com'
                # LDAP property used for searching, ie. login username needs to match value in sAMAccountName property in LDAP
                  LDAP_SEARCH_PROPERTY = 'did'
                    LDAP_SEARCH_SUFFIX = None

                      # Names of LDAP properties on user account to get email and full name
                        LDAP_EMAIL_PROPERTY = 'mail'
                          LDAP_FULL_NAME_PROPERTY = 'cn'
```
# ------------------

is something wrong?

**Comment by martin-sa** [comment]
What indications do you have of the connection being successful? How have you attempted to debug your problem?

Without digging into your exact configuration, I notice that you are not posting the contents of your dist/js/conf.json in taiga-front/. Did you set loginFormType to ldap in it?

**Comment by flyingcircle** [comment]
With no further info, closing
