### ISSUE TITLE
Unable to login taiga after ldap integration -- invalid login type

### ISSUE THREAD

**Issue by hemantjos** [ensky/taiga-contrib-ldap-auth#25]
Post ldap integration I am unable to login:

getting error when trying to login through bash script

---

curl -X POST \
  -H "Content-Type: application/json" \
  -d '{
          "type": "ldap",
          "username": "B000000",
          "password": "xxxxxx"
      }' \
  http://192.168.235.132/api/v1/auth

---

{"_error_type": "taiga.base.exceptions.BadRequest", "_error_message": "invalid login type"}

---

Same error in auth when seen through chrome

config.json

---

{
    "api": "http://192.168.235.132/api/v1/",
    "eventsUrl": "ws://192.168.235.132/events",
    "debug": "true",
    "publicRegisterEnabled": false,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": []
}

---

local.py

---

from common import *

MEDIA_URL = 'http://192.168.235.132/media/'
STATIC_URL = 'http://192.168.235.132/static/'
ADMIN_MEDIA_PREFIX = 'http://192.168.235.132/static/admin/'
SITES['front']['scheme'] = 'http'
SITES['front']['domain'] = '192.168.235.132'

SECRET_KEY = 'theveryultratopsecretkey'

DEBUG = True
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = False
# DEFAULT_FROM_EMAIL = "hemant041177@gmail.com"

SERVER_EMAIL = DEFAULT_FROM_EMAIL
# Uncomment and populate with proper connection parameters
# for enable github login/singin.
# GITHUB_API_CLIENT_ID = "yourgithubclientid"
# GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"

INSTALLED_APPS += ['taiga_contrib_ldap_auth']

LDAP_SERVER = 'ldap://10.5.140.199'
LDAP_PORT = 389
# Full DN of the service account use to connect to LDAP server and search for login user's account entry
# If LDAP_BIND_DN is not specified, or is blank, then an anonymous bind is attempated

LDAP_BIND_DN = 'xxxxx'
LDAP_BIND_PASSWORD = 'xxxxx'  # eg.
# Starting point within LDAP structure to search for login user

LDAP_SEARCH_BASE = 'DC=xxxxx,DC=xxxxx,DC=xxxx'
# LDAP property used for searching, ie. login username needs to match value in sAMAccountName property in LDAP

LDAP_SEARCH_PROPERTY = 'sAMAccountName'
LDAP_SEARCH_SUFFIX = None  # '@example.com'
# Names of LDAP properties on user account to get email and full name

LDAP_EMAIL_PROPERTY = 'mail'
LDAP_FULL_NAME_PROPERTY = 'name'

---

pip list 

---

taiga@osboxes:~$ cd taiga-back/
taiga@osboxes:~/taiga-back$ workon taiga
(taiga)taiga@osboxes:~/taiga-back$ pip list
amqp (1.4.7)
anyjson (0.3.3)
billiard (3.3.0.22)
bleach (1.4.2)
celery (3.1.19)
cssselect (0.9.1)
cssutils (1.0.1)
diff-match-patch (20121119)
Django (1.8.6)
django-ipware (1.1.2)
django-jinja (1.4.1)
django-pgjson (0.3.1)
django-pglocks (1.0.2)
django-picklefield (0.3.2)
django-sampledatahelper (0.3)
django-sites (0.8)
django-sr (0.0.4)
django-transaction-hooks (0.2)
django-transactional-cleanup (0.1.15)
djmail (0.11.0)
djorm-pgarray (1.2)
easy-thumbnails (2.2.1)
fn (0.4.3)
future (0.15.2)
gunicorn (19.3.0)
html5lib (0.9999999)
Jinja2 (2.8)
kombu (3.0.32)
ldap3 (1.0.3)
lxml (3.5.0b1)
Markdown (2.6.4)
MarkupSafe (0.23)
Pillow (2.9.0)
pip (1.5.4)
premailer (2.9.6)
psycopg2 (2.6.1)
pyasn1 (0.1.9)
pycrypto (2.6.1)
Pygments (2.0.2)
pyjwkest (1.0.7)
pytz (2015.7)
raven (5.8.1)
redis (2.10.3)
requests (2.8.1)
sampledata (0.3.7)
setuptools (2.2)
six (1.10.0)
taiga-contrib-ldap-auth (0.0.5)
Unidecode (0.04.18)

---

**Comment by martin-sa** [comment]
I doubt this to be an issue with the plugin. It looks like a misconfiguration to me. At least the following line is missing in conf.json:

"loginFormType": "ldap"
