### ISSUE TITLE
Inviting new project members and the relationship to ldap

### ISSUE THREAD

**Issue by nebulade** [ensky/taiga-contrib-ldap-auth#26]
Hi.

I have setup ldap and it works well with the ldap users. Now I would like to know what the strategy is, in case I want to add team members. If the email of the new member matches one of an user, who had already logged into taiga, everything is fine. But when I invite a new email address, that user would get an invitation mail which allows him to sign up. If that is intended, then the problem is, that this user would not be able to login anymore, since the LDAP auth would fail. 

So I would like to know what the direction for this extension will be. Either disable new signups (which are outside the ldap accounts) or allow to let the auth "fall through" if there is no ldap match found? (The latter seems to be popular for other server apps, but it has the drawback of a potential user clash)

Thanks

**Comment by ensky** [comment]
seems duplicated with #18
