### ISSUE TITLE
Login issues with some users

### ISSUE THREAD

**Issue by cmthomps** [ensky/taiga-contrib-ldap-auth#33]
Is there a way to see the an authentication error log?  I've configured Taiga to connect to our Active Directory server.  Some users are able to login so I know it is working.  However, some users are getting a bad username/password error and I'm looking to debug that problem.

Thanks

**Comment by cmthomps** [comment]
Discovered that there is a case issue.  It appears that what happened was that a user registered with there email in all lower case.  But when the project owner sent an invitation they used a mixed case email address.  Taiga seemed to "sort of" link the two but not completely and it was messing up the users login.  I went into the database and changed the email address to all lowercase and it started working.

**Comment by flyingcircle** [comment]
#15 Duplicate
