### ISSUE TITLE
Error installing via pip, no encoding provided.

### ISSUE THREAD

**Issue by markkwasnick** [ensky/taiga-contrib-ldap-auth#39]
SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_ldap_auth/**init**.py on line 2, but no encoding declared;

Specifically:
# Copyright (C) 2014 Jesús Espino jespinog@gmail.com

**Comment by flyingcircle** [comment]
same as #14 
use python3 / pip3

**Comment by markkwasnick** [comment]
I suppose this makes it very obvious for you to to python 3, at least. Updated my automation with pip3 as executable and it worked.
