### ISSUE TITLE
ldap auth not working in invitation request

### ISSUE THREAD

**Issue by nsaintot** [ensky/taiga-contrib-ldap-auth#4]
Everything is in the title.
The ldap auth is not working when trying to login in invitation request.

Thank you in advance.

**Comment by jespino** [comment]
I have to check it in taiga-back and taiga-front, maybe a problem in the the taiga (core) application.

Thank you for the feedback :smile:

**Comment by alex8092** [comment]
I have watch this bug, but the bug come from taiga directly, the plugin it's just not call from taiga/auth/services.py
