### ISSUE TITLE
active directory and bind dn

### ISSUE THREAD

**Issue by ssplatt** [ensky/taiga-contrib-ldap-auth#5]
I don't see any errors produced anywhere but this doesn't appear to be working with Active Directory, and more specifically, it doesn't look like there is any compatibility with LDAP systems that do not use anonymous bind.

**Comment by ensky** [comment]
This feature will be available soon since there is a pull request from @artlepool try to solve this problem.
https://github.com/ensky/taiga-contrib-ldap-auth/pull/3

**Comment by ensky** [comment]
Thanks to @artlepool, This issue should be fixed in https://github.com/ensky/taiga-contrib-ldap-auth/pull/3
