### ISSUE TITLE
Where is loginFormType in dist.js? Which LDAP account is the admin?

### ISSUE THREAD

**Issue by jdkruzr** [ensky/taiga-contrib-ldap-auth#50]
The installation instructions say to change this variable:

"loginFormType": "ldap",

This isn't found in the file in the installation instructions. How do we get the front end to ask for LDAP logins? And after we do that, how do we establish which LDAP login is the admin?

**Comment by martijnbastiaan** [comment]
Don't worry about it not being present by default. You can add it yourself. If you want to confirm it's working, open up a network console and login. You will see that the body of your POST request to `/api/v1/auth` looks like:

```json
{"username":"xxxx","password":"xxxxxxx","type":"ldap"}
```

You can verify that the plugin is actually being called by reviewing the server reply. If if has an error message resembling:

```
LDAP account or password incorrect: {'error_message': 'Username or password incorrect'}
```

The LDAP plugin is working. The default auth mechanism of Taiga will differentiate between missing users and wrong passwords (which is a security issue IMO).
