### ISSUE TITLE
LDAP-StarTTLS

### ISSUE THREAD

**Issue by Zwordi** [ensky/taiga-contrib-ldap-auth#58]
Hello Everyone,

I tried unsucessfully to connect my NethServer to taiga using the plugin.
The trick about Nethserver is that it user STARTTLS on 389 port so i got this as an answer after what i think to be a correct config.

> Error connecting to LDAP server: (LDAPSocketOpenError('socket ssl wrapping error: EOF occurred in violation of protocol (_ssl.c:645)',),)

My config:
>INSTALLED_APPS += ["taiga_contrib_slack","taiga_contrib_ldap_auth"]
>
>
>
>LDAP_SERVER = 'ldaps://10.0.0.11'
>LDAP_PORT = 389
>

>LDAP_BIND_DN = 'cn=ldapservice,dc=directory,dc=nh'
>LDAP_BIND_PASSWORD = '*************'   # eg.

>LDAP_SEARCH_BASE = 'ou=People,dc=directory,dc=nh'

>LDAP_SEARCH_PROPERTY = 'uid'
>LDAP_SEARCH_SUFFIX = None # '@example.com'`

I can work whitout a working Ldap for now but i would appreciate to collaborate with that issue as i really belive that Taiga+LDAP is a good think for compagny who are doing Agile Dev.

Regards,
Zwordi

**Comment by Zwordi** [comment]
Hello,

I manage to have it working.
Thanks

**Comment by FabricioCabeca** [comment]
Hi @Zwordi
 
did you manage to make it work with STARTTLS or LDAPS, or you simply dropped the secure layer ? If it was the former would you mind explaining what fixed your issue ? It may help me and others

Thanks

**Comment by Zwordi** [comment]
I will copy-paste my config asap :).

**Comment by Zwordi** [comment]
Hi,
Sorry for the delay.
```
INSTALLED_APPS += ["taiga_contrib_slack","taiga_contrib_ldap_auth"]
LDAP_SERVER = 'ldaps://YYYY'
LDAP_PORT = 636

# Full DN of the service account use to connect to LDAP server and search for login user's account entry
# If LDAP_BIND_DN is not specified, or is blank, then an anonymous bind is attempated
LDAP_BIND_DN = 'YYYYYYYYYY'
LDAP_BIND_PASSWORD = 'XXXXXXXXX'   # eg.
# Starting point within LDAP structure to search for login user
LDAP_SEARCH_BASE = 'ou=People,dc=AAAAAAAA'
# LDAP property used for searching, ie. login username needs to match value in sAMAccountName property in LDAP
LDAP_SEARCH_PROPERTY = 'uid'
LDAP_SEARCH_SUFFIX = None # '@example.com'

# Names of LDAP properties on user account to get email and full name
LDAP_EMAIL_PROPERTY = 'mail'
LDAP_FULL_NAME_PROPERTY = 'cn'
```

**Comment by FabricioCabeca** [comment]
Thanks Zwordi !

So it is indeed LDAPS and not STARTTLS. It would be nice if this plugin could also support STARTTLS as it is an official security extension, LDAPS while widely used is not technically specified anywhere.
