### ISSUE TITLE
ldaps connection to active directory failing silently

### ISSUE THREAD

**Issue by ssplatt** [ensky/taiga-contrib-ldap-auth#6]
with the new AD options, I set the port to 636 and LDAP_SERVER = 'ldaps://myip'. I've got the bind_dn, password, search base, and search property set to the same values I use on several other apps like Gitlab. I also set  "publicRegisterEnabled": false, in taiga-front-dist/dist/js/conf.json which I am assuming is proper since everyone I want to authenticate is already in AD.  Circus starts fine, and I can't find any log info on what may be happening. Even if I manually start taiga-back using "workon taiga; python manage.py runserver" I see nothing. If you can think of how I can get some debug info, I'd love to provide more info.

**Comment by artlepool** [comment]
Hi @ssplatt 

Have you used the development tools in your browser to see what the auth API call is returning?

In the Network pane of the Chrome dev tools, you should see a call to the "auth" API endpoint. What does it report as the status code and what's the response from the api?
(Don't know which browser you are using, but should be the same kind of thing in other browser dev tools)

Alternatively you could call the API directory from a bash prompt and see what it says:

```
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{
          "type": "ldap",
          "username": "USERNAME",
          "password": "PASSWORD"
      }' \
  https://TAIGA_URL/api/v1/auth
```

Let me know what you can find out..

**Comment by ssplatt** [comment]
that was a huge help. helped me work through several things that were holding me back but it was all on my end. Thanks for the help and hopefully the slow login/bind is figured out soon too.
